### ISSUE TITLE
Surely this is a mistake in macro

### ISSUE THREAD

**Issue by aaron-michaux** [realnc/frobtads#7]
Referring to `tads3/vmrun.cpp:1046`

```
#define true_for_cond(v)                       \
   ((v)->typ == VM_TRUE || (v)->typ == VM_ENUM \
    || ((v)->typ == VM_INT && !(v)->val.intval == 0))
```

Surely this is a mistake. The expression `!(v)->val.intval == 0` is equivalent to `(!(v)->val.intval) == 0`

Surely it should be:

```
#define true_for_cond(v)                       \
   ((v)->typ == VM_TRUE || (v)->typ == VM_ENUM \
    || ((v)->typ == VM_INT && (v)->val.intval != 0))
```

**Comment by realnc** [comment]
It is actually supposed to be `(!(v)->val.intval)`. The code was changed to make this more explicit in the "next" branch:

https://github.com/realnc/frobtads/blob/next/tads3/vmrun.cpp#L1112

It's a stylistic choice by the code's author (Mike Roberts):

> The code is correct, and it was intentional, although it probably is unnecessarily unclear.  It's explicitly applying a `!` operator to the integer value, which will yield 1 if the value is zero or 0 if the value is non-zero, then checking that the result is exactly 0 - therefore true if the value was non-zero and false if the value is zero.  The idiom is roughly the `!!` operation you often see javascript coders use - which isn't really necessary in C++, but it's there to document the intent that this is a boolean rather than integer operation.  For C it's certainly equivalent to just say `(v)->val.intval != 0`.

The "next" branch has post-release TADS base code updates in it that MR sent me a couple years ago. Unfortunately, the future of TADS in general is unclear at this point, with upstream having been inactive for years now, so I don't know when it can be merged into master :-/ I might merge it anyway at some point.
